# Open API Spec documentation: https://swagger.io/docs/specification/about/


#this is a simple lost lugguage claim API for a flight company.
#This is not the most optimum API and I know it, but this is a very basic skeleton of an API

openapi: "3.0.0"
servers:
  - url: https://api.example.com/v1 
info:
  title: Lost Baggage Claim API
  version: 1.0.0
paths:
  /create_claim/{customerID,flightID,baggageID,itemList}:
    post:
      summary: Create a new baggage claim
      description: |
        Creates a new baggage claim given the inputs from the user.
      parameters:
        - name: customerId
          description: customer identification number
          in: path
          required: true
          schema:
            type: string
          example: "202-sdd-324-sss-234-dsf"
        - name: flightID
          description: Flight number of the flight where the resepected customer lost their baggage
          in: path
          required: true
          schema:
            type: string
          example: "QR 707"
        - name: baggageID
          description: Tag numbers from their lugguage tag
          in: path
          required: false
          schema:
            type: string
          example: "5ca94d88036709a43a429a2b"
        - name: itemList
          description: This is where the user lists their items lost.
          in: path
          required: true
          schema:
            type: object
          example: {"item1":"generic handbag-black"}

          
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  customerID: 
                    type: string
                  flightID:
                    type: string
                  data:
                    type: object 
              # examples syntax: https://swagger.io/docs/specification/2-0/adding-examples/                    
              example:
                - claimID: 6a05e510-12ee-47b1-a7a7-2e4259d24809
                  data: {
                    "customerID": "0a41c6e5-5ad9-4412-ac5c-fc4cc13e2d6c",
                    "flightID": "a40ea1f4-b2f0-4904-9a3c-85c27efeca92",
                    "baggageID": "5ca94d88036709a43a429a2b",
                    "itemList": {"item1":"generic handbag-black"},
                  }                    

      responses:
        '200':
          description: |
            Returns success status and a claim ID so that the customer can keep track of it
          content:
            application/json:
              schema:
                type: object
                properties:
                  claimID:
                    type: string
                    example: 
                      - "6a05e510-12ee-47b1-a7a7-2e4259d24809"
        '500': 
          description: |
            Returns detailed error explanation in baggage claim was unable
            to fulfil the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to the baggage claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'

  /track_claim/{claimId}:
    get:
      summary: Get Lost Baggage Claim
      description: |
        Get the status of a lost baggage claim from a provided Claim ID
      parameters:
        - name: claimID
          description: claim identification number
          in: path
          required: true
          schema:
            type: string
          example: "af04e7c0-1a57-44bc-81a4-d8b3fd0f0f56"
       
      responses:
        '200':
          description: success returns list of events with details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: 
                    claimID: 
                      type: string
                      example: "af04e7c0-1a57-44bc-81a4-d8b3fd0f0f56"
                    data:
                      type: object 
                      example: {
                        "customerID": "a1d5b69e-aefb-4a39-ae5c-affbe6961d60",
                        "flightID": "9f0bbc6a-f199-4238-91f5-15215c0971fe",
                        "baggageID": {"bag1":"5ca95c1b5eb664a11584f8cd"},
                        "itemList": {
                        "item1":"Black Samsonite Lugguage"
                        },
                        "status": "Inquery ongoing",
                    }
        '500': 
          description: |
            Returns detailed error explanation in case baggage claim was unable
            to fulfil the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to the baggage claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorObject'
                # examples syntax: https://swagger.io/docs/specification/2-0/adding-examples/                    
                example:
                  - claimID: af04e7c0-1a57-44bc-81a4-d8b3fd0f0f56
                    data: {
                      "customerID": "a1d5b69e-aefb-4a39-ae5c-affbe6961d60",
                      "flightID": "9f0bbc6a-f199-4238-91f5-15215c0971fe",
                      "baggageID": {"bag1":"5ca95c1b5eb664a11584f8cd"},
                      "itemList": {
                        "item1":"Black Samsonite Lugguage"
                      },
                      "status": "Inquery ongoing",
                    }
components:
  schemas:
    ErrorObject:
      type: object
      properties:
        errorId:
          type: integer
        description:
          type: string
        details:
          type: string
      example:
        errorId: 2345
        description: "Could not connect to database"
        details: "Please contact sysadmin"
